apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample01
  labels:
    app: sample01
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sample01
  template:
    metadata:
      labels:
        app: sample01
    spec:
      containers:
        - name: sample01
          image: docker.io/jojang91/sample01:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 1024Mi
            requests:
              cpu: "1"
              memory: 512Mi
#          args:
#            - -cpus
#            - "1"

#      minReplicas: 1
#      maxReplicas: 10
#      targetCPUUtilizationPercentage: 50

          #new--
#          readinessProbe:
#            httpGet:
#              path: /actuator/manage-f9product/health #/actuator/health
#              port: 8080
#            initialDelaySeconds: 10
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 10
#          livenessProbe:
#            httpGet:
#              path: /actuator/manage-f9product/health #/actuator/health
#              port: 8080
#            initialDelaySeconds: 120
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 5
