apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample01
  labels:
    app: sample01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample01
  template:
    metadata:
      labels:
        app: sample01
    spec:
      containers:
        - name: sample01
          image: docker.io/jojang91/sample01:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 1024Mi
            requests:
              cpu: "1"
              memory: 512Mi
          env:
            - name: DATASORUCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: username
            - name: DATASORUCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: password