spring:
   profiles:
     group:
       "default": "default,common"
       "docker": "docker,common"
       "local": "default,common"
       "dev":  "dev,common"
       "prod": "prod,common"

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: "default"

  application:
    name: testPostgres

  datasource:
    name: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${DATASORUCE_USERNAME:test}
    password: ${DATASORUCE_PASSWORD:test}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-test-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: "docker"

  application:
    name: testPostgres

  datasource:
    name: postgresql
    url: jdbc:postgresql://192.168.101.80:5432/postgres
#    url: jdbc:postgresql://my-release-postgresql.default.svc.cluster.local:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${DATASORUCE_USERNAME:test1}
    password: ${DATASORUCE_PASSWORD:test1}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-test-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true


---
spring:
  config:
    activate:
      on-profile: "common"
